App\Quiz\Domain\Question:
  type: entity
  table: question
  repositoryClass: App\Quiz\Domain\QuestionRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    image:
      type: string
      length: 255
      nullable: false
    content:
      type: string
      nullable: false
    password:
      type: string
      length: 64
      nullable: false
    oneToMany:
      user:
        targetEntity: 'Answer'
        joinColumn:
          name: author_id
          referencedColumnName: id
