version: '3'

services:
  php-fpm:
    build:
      context: ./docker/php-fpm
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
    volumes:
      - ./symfony:/var/www
    ports:
      - "3001:3001"

  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./symfony:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/logs:/var/log
    depends_on:
      - php-fpm
    ports:
      - "80:80"
      - "443:443"


