App\User\Domain\User:
  type: entity
  table: user
  repositoryClass: App\User\Domain\UserRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    email:
      type: string
      length: 180
      unique: true
      nullable: false
    username:
      type: string
      length: 180
      unique: true
      nullable: true
    password:
      type: string
      length: 64
      nullable: false
    roles:
      type: json
      options:
        default: []
      nullable: false
